//初始化用户信息
const INIT_USER_INFO = `INIT_USER_INFO`;
//用户信息
const USER_INFO = `USER_INFO`;
//修改用户昵称
const CHANGE_USER_NICK_NAME = `CHANGE_USER_NICK_NAME`;
//用户生日
const USER_INFO_BRITHDAY = `USER_INFO_BRITHDAY`;
//用户性别
const USER_INFO_SEX = `USER_INFO_SEX`;
//性别
const USER_SEX = `USER_SEX`;
//退出登录
const LOGIN_OUT = `LOGIN_OUT`;
//初始化用户收货地址
const INIT_USER_SHOPPING_ADDRESS = `INIT_USER_SHOPPING_ADDRESS`;
//增加收货地址
const ADD_USER_SHOPPING_ADDRESS = `ADD_USER_SHOPPING_ADDRESS`;
//删除收货地址
const DELETE_USER_SHOPPING_ADDRESS = `DELETE_USER_SHOPPING_ADDRESS`;
//修改收货地址
const CHANGE_USER_SHOPPING_ADDRESS = `CHANGE_USER_SHOPPING_ADDRESS`;

//购物车初始化数据
const INIT_SHOP_CART = `INIT_SHOP_CART`;
//添加商品
const ADD_GOODS = `ADD_GOODS`;
//添加商品到购物车
const ADD_TO_CART = `ADD_TO_CART`;
//减少商品
const REDUCE_GOODS = `REDUCE_GOODS`;
//单个商品选中
const SINGLE_SELECT_GOODS = `SINGLE_SELECT_GOODS`;
//全选选中
const ALL_SELECT_GOODS = `ALL_SELECT_GOODS`;
//删除选中商品
const DELETE_SELECT_GOODS = `DELETE_SELECT_GOODS`;
//选中商品数量
const SELECTED_GOODS_COUNT = `SELECTED_GOODS_COUNT`;
//选中商品
const SELECTED_GOODS = `SELECTED_GOODS`;
//选中商品价格
const SELECTED_GOODS_PRICE = `SELECTED_GOODS_PRICE`;
//删除所有商品
const DELETE_ALL_GOODS = `DELETE_ALL_GOODS`;

export {
  INIT_USER_INFO,
  USER_INFO,
  INIT_SHOP_CART,
  ADD_GOODS,
  ADD_TO_CART,
  CHANGE_USER_NICK_NAME,
  USER_INFO_BRITHDAY,
  USER_INFO_SEX,
  USER_SEX,
  LOGIN_OUT,
  INIT_USER_SHOPPING_ADDRESS,
  ADD_USER_SHOPPING_ADDRESS,
  DELETE_USER_SHOPPING_ADDRESS,
  CHANGE_USER_SHOPPING_ADDRESS,
  REDUCE_GOODS,
  SINGLE_SELECT_GOODS,
  ALL_SELECT_GOODS,
  DELETE_SELECT_GOODS,
  SELECTED_GOODS_COUNT,
  SELECTED_GOODS,
  SELECTED_GOODS_PRICE,
  DELETE_ALL_GOODS
};
